### ISSUE TITLE
[BETA-TESTING] Help wanted!

### ISSUE THREAD

**Issue by Unbrick** [krokofant/JodelXposed#65]
@Hawpe , @schoftwaer , @ChavezD , @Keagel , @krokofant and everyone else reading this!

Hey guys, it's me again! We are trying to constantly improve the quality of our releases. We'd love to have someone with different phones to test upcoming releases before a buggy release is going online!

Current status: Fixed most of the reported bugs. 

Additions compared to the last official release:

- Added time formatting
- Changed distances from text to kilometers
- Added ability to search for hashtags
- Fixed many bugs (thanks to the community!)
- No layout inflation from XML files anymore, this is all done programatically

Known issues:

- Track poster in comments is broken (Issue already created)
- Keyboard in the new "Search for hashtags" sometimes behaves weired

Current suggestions:

- Add items in the fast location switcher dynamically
- Disable only special kind of notifications (like 5 upvotes notification)

Current beta (05.04.2017): 
[JodelXposed_2_4_9.zip](https://github.com/krokofant/JodelXposed/files/899697/JodelXposed_2_4_9.zip)

If you have some new suggestions or want to report a bug, add [me ](https://telegram.me/ubrick) on [Telegram](https://telegram.org) messenger! (Thanks to krokofant!)

**Comment by ChavezD** [comment]
Hey there,
I sadly can't test it anymore on my primary device since my new HTC already got Android 7 (wich has no Xposed support yet :( )..
I think there no other way to get jodel Xposed to work, is there?
Maybe I will have some free time tomorrow and I can test it on my old Huawei, after that I could possibly tell you if it's working tomorrow evening.

Von: Unbrick
Gesendet: Sonntag, 19. März, 00:06
Betreff: [krokofant/JodelXposed] [BETA-TESTING] Help wanted! (#65)
An: krokofant/JodelXposed
Cc: ChavezD, Mention

@Hawpe<https://github.com/Hawpe> , @schoftwaer<https://github.com/schoftwaer> , @ChavezD<https://github.com/ChavezD> , @Keagel<https://github.com/Keagel> , @krokofant<https://github.com/krokofant> and everyone else reading this!

Hey guys, it's me again! We are about to push a new release of JodelXposed with some new features in it.
Main additions are:

Added a new date / time formatting options to get the post time exactly Added distance formatting to display the distance in kilometers instead of "close" or something Added a the abitity to search for hashtags without posting them

The fast scroll down is still work in progress, it shoudn't do anything by now (but it should appear!). (Tecnical details: there are only loaded 20 posts a time so fastscrolling threads with >20 posts isn't working, we are trying to find a fix!)

Now i wanted to ask you whether you would mind about giving the new version a try and report any bugs or broken features in here before we are pushing a official release!

Here you can grab the 2.4.8-beta version:
jx_2.4.8_beta.zip<https://github.com/krokofant/JodelXposed/files/852813/jx_2.4.8_beta.zip>

**Comment by schoftwaer** [comment]
Thank you for inviting in this, I installed it and made some tests already.
But first of all, which Jodel Version is supposed to be to work?
I was using 4.36.0 and because of an error I checked the log where it says "JodelTarget 4.37.5"
After updating it says by opening Jodel "This version of Jodel is not supported yet" or something like that.

**Comment by Unbrick** [comment]
@ChavezD Don't stress yourself out but i'm happy you want to test it. Afaik there is no possibility of Xposed on Android N but Rovo89 is working on it!

@schoftwaer The jodel target version is 4.37.5 and some of the hooks are also version specific. But it should work after the "This version of Jodel is not supported yet" message, close it and reopen Jodel. Should do the trick.

**Comment by schoftwaer** [comment]
So, I tested again with 4.37.5 now and most of the functions are working. The time formatting works, except Jodel default. Choosing Jodel default or YYYY:MM:DD HH:MM:SS makes no difference!
And again, when changing the location with the location picker, the picture in the Xposed Menu doesn't change. Tapping on the JX Change location tab, there is the right picture/location shown.
Fastscrolling is shown correctly, but without function (as you mentioned).

One thing I want to mention, using the color picker works when you want to post text only. If I upload images from gallery or take a picture the color is the original one.

Oh, now I saw you wrote the working jodel version on top of the new features. Sorry then, for the unnecessary question. Maybe you have an Idea how I can restore my Karmapoints? I needed to uninstall both (Jodel and JX) to make it work again but now my Karma is gone although it says "Backup restored".

**Comment by Unbrick** [comment]
Fixed the map not changing and the time formatting of YYYY:MM:DD HH:MM:SS .

I'm working on the color picker when picking a image but this seems tricky. 

Regarding your karma: Do you have your UDI somewhere?

**Comment by Keagel** [comment]
All of the new features seem to work fine for me, except the distance still shows as close/very close in the comments instead of displaying the actual distance in kilometers

**Comment by schoftwaer** [comment]
@Unbrick did you fix time formatting for "Jodel default" also? there was the issue.

I restored an old backup and copied my UDI. I tried to put it in the json file under "uid" and set that part to true, but nothing happened. Am I doing something wrong?

**Comment by Unbrick** [comment]
@schoftwaer Cleared app data after putting UDI in jodel-settings?

@Keagel I'm adding the kilometers in the PostDetailView this evening! And yes, you sadly picked up the "old" version which contains the bugs. I'll upload a new one as soon as i have fixed everything!

**Comment by schoftwaer** [comment]
Yes, now I get error "403 Forbidden" when opening jodel.

**Comment by Unbrick** [comment]
@schoftwaer
Try deleting your jodel-settings.json and Jodels app data, then fire up Jodel again. Should do the trick!

**Comment by schoftwaer** [comment]
Nope, same error. I also tried deleting JX with it's json file and uninstalling Xposed. cleared jodel data once again but no success. 
I don't want to spam here with my own off-topic issue, when there is a way to keep in contact with you for help outside from this github "issue" I would be glad. Otherwise I try some things for myself to get jodel running again. :)

**Comment by Keagel** [comment]
I don't know if it's the right word in English but as a "Peace keeper" (moderator I guess?) when you go on reported posts it only shows the fastscroll thingy

**Comment by Keagel** [comment]
Also I seem to constantly get "access failed" errors telling me to update the app every time I try to vote or comment

**Comment by Unbrick** [comment]
@Keagel I'll check that, in my deug build it's working like a charm. I'll make a fresh build this afternoon so you can install it. Also I'm sadly no mod so I can't do much about it, I'd need a mod udi in order to check that menu.

@schoftwaer Do you have Telegramm Messenger? If you do, add me (Unbrick) and I'll try to solve your issue. I'll post the new build in here so you can test it.

**Comment by Keagel** [comment]
It's actually kinda weird because it doesn't happen all the time, for example I had the version installed for a few hours and I was able to comment/vote but after a while I constantly had this error "Access failed, please update your app or contact the support" (which disappears if I disable JX)

**Comment by Unbrick** [comment]
Could you try to get a logcat of the app when the error message appears next time?

**Comment by Keagel** [comment]
Sure. There's no error for now but I'll send you the logs when it happens again

**Comment by Unbrick** [comment]
Here the "new" release, hope it's not too buggy:

[jx_2_4_8_v33.zip](https://github.com/krokofant/JodelXposed/files/859235/jx_2_4_8_v33.zip)

**Comment by Keagel** [comment]
Are you sure it's a new release? The kilometers in the PostDetailView don't show and the location image still doesn't change

**Comment by Unbrick** [comment]
Intention of this release was just to fix the "access failed" error. Had no time until now to fix it, have to study for my finals.

**Comment by Keagel** [comment]
Oh alright. The "access failed" error hadn't happened again so I can't really tell you if it's fixed

**Comment by Keagel** [comment]
Well it just happened again. Here's the [screenshot](http://i.imgur.com/0nOryCm.png)
And the logs:

[Uploading alogcat.2017-03-22-17-38-20+0100.txt…]()
[Uploading alogcat.2017-03-22-17-37-09+0100.txt…]()

No errors in the xposed logs. A simple reboot fixes it. When this error happens I can't comment/vote/share (the new feature).

**Comment by Unbrick** [comment]
Which Jodel version are you on?

**Comment by Keagel** [comment]
4.37.5, there is no newer version. I believe they updated the app without going through the play store since the sharing option wasn't here 2 days ago

**Comment by Unbrick** [comment]
Well I'm on 4.38.3...

**Comment by Keagel** [comment]
Well it's weird, going to download the apk from an external site then

**Comment by Unbrick** [comment]
Awsome, thank you! Mind to add me on Telegramm (Unbrick)?

**Comment by Keagel** [comment]
You're talking about the "Unbrick" group right?

**Comment by Unbrick** [comment]
Didn't knew there's a group named this, no I got the nickname unbrick

**Comment by Keagel** [comment]
Well every time I search for your username only the group shows up

**Comment by schoftwaer** [comment]
I only found the Unbrick group, too. If you don't had a new person contacted you yesterday, then I added someone different :D

**Comment by ChavezD** [comment]
So i have tried to restore a backup from my old Huawei P8 (with Xposed installed) to my new HTC u ultra (Android 7 without Xposed available yet) and it can't be started. Error 477 and 429 so far after opening the app and accepting the permissions and so on.

On telegram I also didn't find you @unbrick, only some group, too.

**Comment by krokofant** [comment]
@Unbrick @Keagel @schoftwaer @ChavezD 
Unbrick is actually [Ubrick](https://telegram.me/ubrick) on Telegram (click the link) 😆

**Comment by Unbrick** [comment]
Oh my bad, thanks 😂

**Comment by clempe** [comment]
I also like to participate the beta test. My Telegram username _clempe_ if needed

**Comment by Hehe55** [comment]
Downloaded the 2.4.8 beta a while ago.    Post ID within a Jodel stopped working for me 2 days ago.  Everyone is labeled as #1.  Using 4.37.5

**Comment by Unbrick** [comment]
@clempe 
Of course you can join, just download the apk provided in the first post and report back!

@Hehe55 created an issue, expierienced that one too!

**Comment by krokofant** [comment]
The notification *blocker*, if you will, could also be used to filter out duplicates of notifications for the same threads.

**Comment by Hehe55** [comment]
MY KARMA tab disappear quite often.  Jodel will crash if I swipe to access my karma if the tab in the top right corner is gone.  App will instantly crashthe moment i press the gallery/camera roll button. JX 2.4.9 and Jodel v4.40.1
